#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""voice-agent - Pipecat Voice Agent

Dual-brain pipeline (fast-slow-brain design §5.1): Speech-to-Text feeds a
common turn-detection segment, then splits into two parallel branches — a
fast brain that talks to the user, and a slow brain that silently deep-dives
in the background and injects material into the fast brain's context.

Generated by Pipecat CLI, since extended per
openspec/changes/fast-slow-brain/design.md.

Required AI services:
- Soniox (Speech-to-Text)
- Openai-compatible gateway (fast + slow LLM)
- ElevenLabs (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

from dataclasses import dataclass

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.evals.transport import EvalTransportParams
from pipecat.frames.frames import ErrorFrame, LLMRunFrame
from pipecat.pipeline.parallel_pipeline import ParallelPipeline
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregator,
    LLMUserAggregatorParams,
)
from pipecat.processors.aggregators.sentence import SentenceAggregator
from pipecat.processors.audio.vad_processor import VADProcessor
from pipecat.processors.consumer_processor import ConsumerProcessor
from pipecat.processors.frameworks.rtvi import RTVIObserverParams, RTVIServerMessageFrame
from pipecat.processors.producer_processor import ProducerProcessor
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.elevenlabs.tts import ElevenLabsTTSService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transcriptions.language import Language
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.turns.user_turn_processor import UserTurnProcessor
from pipecat.turns.user_turn_strategies import ExternalUserTurnStrategies
from pipecat.workers.runner import WorkerRunner

import dual_brain
import prompts
import sentinel
from config import Config, load_config

load_dotenv(override=True)

# R5: validate all required config at startup, fail fast with the full list.
cfg = load_config()

# bot.py —— provider 名 → 构造器。
# 换厂商 = ①这里加一行 ②pyproject 加对应 extras ③改 .env,config.py/tests/管线全不动。
# 构造代码照抄官方事实源:pipecat/cli/registry/service_metadata.py 的 SERVICE_CONFIGS["<name>_stt"]
# (27 家 STT / 32 家 TTS 全在里面,含 import 路径与 extras 包名)。
#
# 2026-08-03 决议(推翻 §6.3 原"只注册一家"拍板,用户已知情确认):本期同时保留
# soniox/deepgram 两家,启动前用 STT_PROVIDER 选,免得以后每次切换都要重连代码。
# 为此把 import 从模块顶部挪进各自构造函数体内做惰性 import——避免"顶部 import
# 无条件全跑,某家 SDK 装不上就拖累另一家也启动不了"的耦合(§6.3 原实测的风险点，
# 惰性 import 后不再成立)。
def _build_soniox_stt(c: Config):
    from pipecat.services.soniox.stt import SonioxSTTService

    return SonioxSTTService(
        api_key=c.stt_api_key,
        settings=SonioxSTTService.Settings(model=c.stt_model, language_hints=[Language.ZH]),
    )


def _build_deepgram_stt(c: Config):
    # Deepgram key 走独立 DEEPGRAM_API_KEY,经 config.py 按 STT_PROVIDER=deepgram
    # 条件必需校验后落到 c.stt_api_key(与 soniox 用同一字段名,值随所选厂商而
    # 变)。不传 model —— c.stt_model 是 Soniox 档位名(stt-rt-v5),混用会错;
    # 留空吃 Deepgram 默认 nova-3-general,该模型自 2026-03-31 起支持中文
    # (zh/zh-CN),经 Deepgram 官方文档核实(§6.3 原判"中文弱于 Soniox"针对的是
    # 旧版 nova-3,已过期)。
    from pipecat.services.deepgram.stt import DeepgramSTTService

    return DeepgramSTTService(
        api_key=c.stt_api_key,
        settings=DeepgramSTTService.Settings(language=Language.ZH, smart_format=True),
    )


STT_BUILDERS = {
    "soniox": _build_soniox_stt,
    "deepgram": _build_deepgram_stt,
}
def _build_elevenlabs_tts(c: Config):
    return ElevenLabsTTSService(
        api_key=c.tts_api_key,
        settings=ElevenLabsTTSService.Settings(
            voice=c.tts_voice, model=c.tts_model, language=Language.ZH
        ),
    )


def _build_cartesia_tts(c: Config):
    # 试用(2026-08-03),同 deepgram STT 惰性 import 的理由。Cartesia key/voice
    # 走独立 CARTESIA_API_KEY/CARTESIA_VOICE_ID,经 config.py 按
    # TTS_PROVIDER=cartesia 条件必需校验后落到 c.tts_api_key/c.tts_voice(与
    # elevenlabs 用同一组字段名)。不传 model,吃 Cartesia 默认 sonic-3.5——经
    # 官方文档核实,该模型 42 种语言里含中文(zh),够用。
    from pipecat.services.cartesia.tts import CartesiaTTSService

    return CartesiaTTSService(
        api_key=c.tts_api_key,
        settings=CartesiaTTSService.Settings(voice=c.tts_voice, language=Language.ZH),
    )


TTS_BUILDERS = {
    "elevenlabs": _build_elevenlabs_tts,
    "cartesia": _build_cartesia_tts,
}


@dataclass
class AssembledPipeline:
    """Everything `run_bot` needs to wire up a session, plus every object the
    U-group structural tests (design §8.2 U3/U5) need to assert on. Not
    frozen — it's a one-shot bag of already-constructed objects handed back
    from `assemble_pipeline`, never mutated after return.
    """

    pipeline: Pipeline
    worker: PipelineWorker
    fast_context: LLMContext
    slow_context: LLMContext
    fast_llm: OpenAILLMService
    slow_llm: OpenAILLMService
    tts: ElevenLabsTTSService
    fast_user_aggregator: LLMUserAggregator
    sentence_aggregator: SentenceAggregator
    producer: ProducerProcessor
    consumer: ConsumerProcessor
    rtvi_observer_params: RTVIObserverParams


def make_pipeline_error_handler(
    slow_llm: OpenAILLMService, slow_material_filter: dual_brain._SlowMaterialFilter
):
    """Build a session-scoped `on_pipeline_error` handler (design §5.2/§6.4/§6.5).

    `ErrorFrame` is a shared upstream system frame used by every processor in
    the pipeline (STT disconnect, TTS 401/429, fast-LLM gateway 500, ...), so
    the handler must attribute each error to its actual source
    (`frame.processor`) before logging — misattributing e.g. a TTS outage as
    `slow-failed` would hide a real "user hears nothing" incident behind a
    "slow brain degraded gracefully" panel message (design §6.4 rationale).

    Only the slow-brain LLM's errors get the `slow-failed` log line + panel
    message; every other source gets the generic `pipeline-error` log line.
    No recovery, no retry, no cleanup of already-injected material — the
    handler doesn't touch `context`/`dual_brain` state at all (design §5.2:
    "慢脑调用失败时,已注入的素材保留在快脑上下文,不做清理").

    `turn` is read from `slow_material_filter.turn` — the same
    log-correlation counter that backs this session's dispatch/inject/
    no-material/abort lines (design §6.4) — instead of an independent
    counter, so `slow-failed` lines stay correlated with the rest of a
    turn's log lines (组末评审 MEDIUM,2026-08-03: an earlier version kept
    its own counter that only advanced on error and drifted out of sync).
    """

    async def handle_pipeline_error(worker, frame: ErrorFrame) -> None:
        if frame.processor is slow_llm:
            turn = slow_material_filter.turn
            logger.info(f"[dual-brain] slow-failed turn={turn} error={frame.error}")
            await worker.queue_frames(
                [RTVIServerMessageFrame(data={"type": "slow-brain-failed", "turn": turn})]
            )
        else:
            logger.info(f"[dual-brain] pipeline-error src={frame.processor} error={frame.error}")

    return handle_pipeline_error


def assemble_pipeline(cfg: Config, transport: BaseTransport) -> AssembledPipeline:
    """Build the dual-brain `ParallelPipeline` worker for one session (design §5.1).

    Split out from `run_bot` so tests can construct it against a fake
    transport (only `.input()`/`.output()` are called) and assert on its
    shape without driving a real `WorkerRunner` loop (design §8.2 U3/U5).
    """
    # Speech-to-Text / Text-to-Speech services — built via provider builders
    # (design §6.3): only the in-use provider is registered per map.
    stt = STT_BUILDERS[cfg.stt_provider](cfg)
    tts = TTS_BUILDERS[cfg.tts_provider](cfg)

    # Fast brain — the only branch that talks to the user.
    fast_llm = OpenAILLMService(
        api_key=cfg.llm_api_key,
        base_url=cfg.llm_base_url,
        settings=OpenAILLMService.Settings(
            model=cfg.llm_model,
            system_instruction=prompts.SYSTEM_PROMPT,
        ),
    )
    # Slow brain — silent deep-dive, feeds material into the fast brain via
    # Producer/Consumer (design §5.2). Same gateway, different model + prompt.
    slow_llm = OpenAILLMService(
        api_key=cfg.llm_api_key,
        base_url=cfg.llm_base_url,
        name="SlowBrainLLM",
        settings=OpenAILLMService.Settings(
            model=cfg.slow_llm_model,
            system_instruction=prompts.SLOW_BRAIN_PROMPT,
        ),
    )

    fast_context = LLMContext()
    slow_context = LLMContext()

    # Both aggregator pairs use ExternalUserTurnStrategies(): turn/VAD
    # management is driven once by the common VADProcessor/UserTurnProcessor
    # segment below, not by each aggregator independently (design §5.1).
    fast_pair = LLMContextAggregatorPair(
        fast_context,
        user_params=LLMUserAggregatorParams(user_turn_strategies=ExternalUserTurnStrategies()),
    )
    slow_pair = LLMContextAggregatorPair(
        slow_context,
        user_params=LLMUserAggregatorParams(user_turn_strategies=ExternalUserTurnStrategies()),
    )

    # Session-scoped filter instance (T5.2) — never the module-level test
    # singleton, see `dual_brain.build_slow_material_filter` docstring.
    slow_material_filter = dual_brain.build_slow_material_filter()
    slow_material_filter.bind_context(slow_context)

    # B5 修法(docs/backlog.md)：旁听快脑原始文本，不经 TTS 排队，供慢脑的
    # 完成注入消息在触发重新生成前提醒快脑"你刚才已经这样回答过"，避免快脑
    # 因看不到自己已答内容而把问题从头重答一遍。会话隔离，同一 rationale
    # 见 `dual_brain.build_fast_answer_tap` docstring。
    fast_answer_tap = dual_brain.build_fast_answer_tap()

    sentence_aggregator = SentenceAggregator()
    producer = ProducerProcessor(
        filter=slow_material_filter,
        transformer=dual_brain.build_slow_material_transformer(fast_answer_tap),
        passthrough=True,
    )
    consumer = ConsumerProcessor(producer=producer)

    # Session-scoped sentinel gate (T4.3) — same one-instance-per-session
    # rationale as the slow-material filter above.
    sentinel_filter = sentinel.build_sentinel_filter()

    vad_processor = VADProcessor(vad_analyzer=SileroVADAnalyzer())
    user_turn_processor = UserTurnProcessor()

    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            vad_processor,
            user_turn_processor,
            ParallelPipeline(
                [
                    # Fast brain — the pipeline's only external output.
                    consumer,
                    fast_pair.user(),
                    fast_llm,
                    fast_answer_tap,
                    sentinel_filter,
                    tts,
                    transport.output(),
                    fast_pair.assistant(),
                ],
                [
                    # Slow brain — no output component in this branch.
                    slow_pair.user(),
                    slow_llm,
                    sentence_aggregator,
                    producer,
                    slow_pair.assistant(),
                ],
            ),
        ]
    )

    rtvi_observer_params = RTVIObserverParams(
        # Slow-brain branch only — the fast LLM must never be ignored
        # (design §5.1.1 R2): its RTVI events drive the client panel.
        ignored_sources=[slow_llm, sentence_aggregator, producer],
        # Second leak path (design §5.1.1): the injection template reaches
        # `messages[-1]` on the fast context and would otherwise surface via
        # `user-llm-text`. `ignored_sources` alone can't catch this.
        user_llm_enabled=False,
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        rtvi_observer_params=rtvi_observer_params,
    )

    worker.event_handler("on_pipeline_error")(
        make_pipeline_error_handler(slow_llm, slow_material_filter)
    )

    return AssembledPipeline(
        pipeline=pipeline,
        worker=worker,
        fast_context=fast_context,
        slow_context=slow_context,
        fast_llm=fast_llm,
        slow_llm=slow_llm,
        tts=tts,
        fast_user_aggregator=fast_pair.user(),
        sentence_aggregator=sentence_aggregator,
        producer=producer,
        consumer=consumer,
        rtvi_observer_params=rtvi_observer_params,
    )


def seed_greeting_messages(fast_context: LLMContext, slow_context: LLMContext) -> None:
    """Add the per-session greeting turn to both contexts (design §5.3).

    A lone "developer"-role message with no user turn gets rejected (400
    invalid argument) by the 8045 gateway (human dogfood 20260801) — use
    "user" instead, for both contexts. The slow brain's message is a no-op
    ("会话开始,用户尚未提问"): it hits the "no analytical value" zero-output
    branch (design §6.7①), so the greeting turn never injects material or
    triggers a supplement. Split out from `run_bot`'s `on_client_ready`
    handler so tests can drive the exact same greeting content without a
    real `WorkerRunner`/RTVI event loop (design §8.1
    test_greeting_turn_emits_no_material).
    """
    fast_context.add_message(
        {"role": "user", "content": "Start by concisely introducing yourself."}
    )
    slow_context.add_message({"role": "user", "content": "(会话开始,用户尚未提问)"})


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    logger.info("Starting bot")

    assembled = assemble_pipeline(cfg, transport)
    worker = assembled.worker
    fast_context = assembled.fast_context
    slow_context = assembled.slow_context

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation (design §5.3).
        seed_greeting_messages(fast_context, slow_context)
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await worker.cancel()

    runner = WorkerRunner(handle_sigint=False)

    await runner.add_workers(worker)
    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Behavioral evals: run with `-t eval` to drive this bot via `pipecat eval`.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
